export const LOGIN_USER = 'LOGIN_USER'
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCESS = 'REGISTER_USER_SUCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_SUCESS'
